const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin.middleware');
const requireCredits = require('../middlewares/requireCredits.middleware');
const Mailer = require('../services/mailer.service');
const surveyTemplate = require('../services/email-templates/survey.template');

const Survey = mongoose.model('surveys'); // different approach then requireing file
// better for testing

module.exports = (app) => {

    app.post('/api/surveys', requireLogin, requireCredits, async (req, res) => {
        // 1. Is user logged in ? -> requireLogin middleware
        // 2. Does user have enough credits ? -> requireCredits
        const { title, subject, body, recipients } = req.body;

        const survey = new Survey({
            title,
            subject,
            body,
            recipients: recipients.split(',').map(email => ({ email: email.trim() })),
            _user: req.user.id, // id auto-generated by mongoose,
            dataSent: Date.now()
        });

        // create and send email
        const mailer = new Mailer(survey, surveyTemplate(survey));
        
        // check if email has been sent 
        try {
            // save survey to db
            await mailer.send();
            await survey.save(); // db operation
            req.user.credits -= 1;
            const newUserState = await req.user.save();
    
            return res.send(newUserState);
        } catch(e) {
            return res.status(422).send({message: e});
        }
    });

    app.get('/api/surveys/thanks', (req, res) => {
        return res.send('Thanks for voting!');
    });
};